#!/bin/bash

ffmpeg -i "/data/ai_box/media/audio/MotorVehicleIllegalParking.mp3" -f wav -ac 2 -ar 16000 -af "afade=t=in:st=0:d=1" "MotorVehicleIllegalParking.wav"
ffmpeg -i "/data/ai_box/media/audio/CrossTheLine.mp3" -f wav -ac 2 -ar 16000 -af "afade=t=in:st=0:d=1" "CrossTheLine.wav"
ffmpeg -i "/data/ai_box/media/audio/CaptureFace.mp3" -f wav -ac 2 -ar 16000 -af "afade=t=in:st=0:d=1" "CaptureFace.wav"
ffmpeg -i "/data/ai_box/media/audio/NoHelmet.mp3" -f wav -ac 2 -ar 16000 -af "afade=t=in:st=0:d=1" "NoHelmet.wav"
ffmpeg -i "/data/ai_box/media/audio/RegionalInvasion.mp3" -f wav -ac 2 -ar 16000 -af "afade=t=in:st=0:d=1" "RegionalInvasion.wav"
ffmpeg -i "/data/ai_box/media/audio/Poppy.mp3" -f wav -ac 2 -ar 16000 -af "afade=t=in:st=0:d=1" "Poppy.wav"
ffmpeg -i "/data/ai_box/media/audio/MissingZebraCrossing.mp3" -f wav -ac 2 -ar 16000 -af "afade=t=in:st=0:d=1" "MissingZebraCrossing.wav"
ffmpeg -i "/data/ai_box/media/audio/ZebraCrossingFading.mp3" -f wav -ac 2 -ar 16000 -af "afade=t=in:st=0:d=1" "ZebraCrossingFading.wav"
ffmpeg -i "/data/ai_box/media/audio/Smog.mp3" -f wav -ac 2 -ar 16000 -af "afade=t=in:st=0:d=1" "Smog.wav"
ffmpeg -i "/data/ai_box/media/audio/EBikeInElevator.mp3" -f wav -ac 2 -ar 16000 -af "afade=t=in:st=0:d=1" "EBikeInElevator.wav"
ffmpeg -i "/data/ai_box/media/audio/PeopleCrowded.mp3" -f wav -ac 2 -ar 16000 -af "afade=t=in:st=0:d=1" "PeopleCrowded.wav"
ffmpeg -i "/data/ai_box/media/audio/Calling.mp3" -f wav -ac 2 -ar 16000 -af "afade=t=in:st=0:d=1" "Calling.wav"
ffmpeg -i "/data/ai_box/media/audio/ShortSleeve.mp3" -f wav -ac 2 -ar 16000 -af "afade=t=in:st=0:d=1" "ShortSleeve.wav"
ffmpeg -i "/data/ai_box/media/audio/Fire.mp3" -f wav -ac 2 -ar 16000 -af "afade=t=in:st=0:d=1" "Fire.wav"
ffmpeg -i "/data/ai_box/media/audio/Trash.mp3" -f wav -ac 2 -ar 16000 -af "afade=t=in:st=0:d=1" "Trash.wav"
ffmpeg -i "/data/ai_box/media/audio/Climbing.mp3" -f wav -ac 2 -ar 16000 -af "afade=t=in:st=0:d=1" "Climbing.wav"
ffmpeg -i "/data/ai_box/media/audio/NonMotorVehicleIllegalParking.mp3" -f wav -ac 2 -ar 16000 -af "afade=t=in:st=0:d=1" "NonMotorVehicleIllegalParking.wav"
ffmpeg -i "/data/ai_box/media/audio/Fighting.mp3" -f wav -ac 2 -ar 16000 -af "afade=t=in:st=0:d=1" "Fighting.wav"
ffmpeg -i "/data/ai_box/media/audio/SleepingOnDuty.mp3" -f wav -ac 2 -ar 16000 -af "afade=t=in:st=0:d=1" "SleepingOnDuty.wav"
ffmpeg -i "/data/ai_box/media/audio/TrafficCongestion.mp3" -f wav -ac 2 -ar 16000 -af "afade=t=in:st=0:d=1" "TrafficCongestion.wav"
ffmpeg -i "/data/ai_box/media/audio/NotReflectiveClothing.mp3" -f wav -ac 2 -ar 16000 -af "afade=t=in:st=0:d=1" "NotReflectiveClothing.wav"
ffmpeg -i "/data/ai_box/media/audio/Staying.mp3" -f wav -ac 2 -ar 16000 -af "afade=t=in:st=0:d=1" "Staying.wav"
ffmpeg -i "/data/ai_box/media/audio/Understaffed.mp3" -f wav -ac 2 -ar 16000 -af "afade=t=in:st=0:d=1" "Understaffed.wav"
ffmpeg -i "/data/ai_box/media/audio/Smoking.mp3" -f wav -ac 2 -ar 16000 -af "afade=t=in:st=0:d=1" "Smoking.wav"
ffmpeg -i "/data/ai_box/media/audio/LicensePlateRecognition.mp3" -f wav -ac 2 -ar 16000 -af "afade=t=in:st=0:d=1" "LicensePlateRecognition.wav"
ffmpeg -i "/data/ai_box/media/audio/Fall.mp3" -f wav -ac 2 -ar 16000 -af "afade=t=in:st=0:d=1" "Fall.wav"
